version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: unless-stopped
    ports:
      - "8050:8025"
      - "1050:1025"
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  notify-service:
    build: ./
    container_name: notify-service
    volumes:
      - .:/usr/local/bin/
    networks:
      - task-network
    depends_on:
      mailhog:
        condition: service_healthy
    restart: unless-stopped
    command: [ "CompileDaemon", "-command=go run main.go" ]

networks:
  task-network:
    external: true
