version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: '${COMPOSE_PROJECT_NAME}-zookeeper'
    restart: unless-stopped
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - task-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: '${COMPOSE_PROJECT_NAME}-kafka'
    restart: unless-stopped
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_PORT}
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ENABLE_KRAFT: "false"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - task-network
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    build: ./docker/
    container_name: '${COMPOSE_PROJECT_NAME}-app'
    volumes:
      - .:/usr/local/bin/
    ports:
      - "${PORT}:${PORT}"
      - "${PORT_DEBUG}:2345"
    networks:
      - task-network
    command: ["sh", "-c", "swag init && ./docker/debug.sh"]
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
networks:
  task-network:
    external: true
